version: "3.4"

# DEV CONFIG: 'docker-compose up' reads it automatically along with the docker-compose.yml file
# See: https://docs.docker.com/compose/extends/

x-common: &common
  build: .
  environment:
    ENVIRONMENT: "dev"
    URLS_BASEPATH: "public"
  restart: "no"
  volumes:
    - ./local:/home/hubbleadm/local
    - ./docs/static:/home/hubbleadm/docs/static
    - ./scripts:/home/hubbleadm/scripts

services:
  nginx:
    image: nginx:1.17
    container_name: hubble-nginx
    restart: always
    depends_on:
      - web
    volumes:
      # Read only config volume
      - ./config/nginx-dev:/etc/nginx/conf.d:ro
      - ./config/nginx-common/snippets:/etc/nginx/snippets:ro
      - ./config/nginx-auth:/etc/nginx/auth
    ports:
      - "80:80"

  web:
    <<: *common
    depends_on:
      - cache
    command: ["./scripts/command-devserver.sh"]
    expose:
      - "8000"

  broker:
    restart: "no"

  celery: *common

  flower:
    <<: *common
    ports:
      - "5555:5555"

  beat: *common

  cache:
    image: memcached:latest
    container_name: hubble-cache
    environment:
      MEMCACHED_CACHE_SIZE: 1024
    hostname: cache

  db:
    restart: "no"
    environment:
      POSTGRES_DB: hubble
      POSTGRES_USER: hubble
      POSTGRES_PASSWORD: hubble
    expose:
      - "5432"
