# BASE CONFIG: applies to all environments, does not work alone
# See: https://docs.docker.com/compose/extends/

# Extension fields
# See: https://docs.docker.com/compose/compose-file/#extension-fields
x-hubble-image: &hubble-image hubble:0.9

services:
  nginx:
    image: nginx:latest
    container_name: hubble-nginx
    environment:
      INTERNAL_IPS: ${INTERNAL_IPS}
    restart: always
    depends_on:
      - web
    volumes:
      - statics:/home/hubbleadm/static

  web:
    image: *hubble-image
    container_name: hubble
    restart: always
    environment:
      SERVICE_TYPE: "web"
      INTERNAL_IPS: ${INTERNAL_IPS}
    volumes:
      - statics:/home/hubbleadm/static
    expose:
      - "8000"

  broker:
    image: rabbitmq:3.8.3
    container_name: hubble-broker
    environment:
      INTERNAL_IPS: ${INTERNAL_IPS}
    restart: always

  celery:
    image: *hubble-image
    container_name: hubble-celery
    environment:
      INTERNAL_IPS: ${INTERNAL_IPS}
    restart: always
    command:
      [
        "celery",
        "--app=hubble",
        "--concurrency=8",
        "--hostname=worker1@%h",
        "--loglevel=INFO",
        "--queues=celery",
        "worker",
      ]
    depends_on:
      - web
      - broker

  flower:
    image: *hubble-image
    container_name: hubble-flower
    environment:
      INTERNAL_IPS: ${INTERNAL_IPS}
    restart: always
    # TODO: Change url prefix to /admin/tasks when having nginx proxy
    command:
      [
        "celery",
        "--app=hubble",
        "--concurrency=8",
        "--db=/home/hubbleadm/tmp/flowerdb",
        "--persistent",
        "--port=5555",
        "flower",
      ]
    depends_on:
      - broker
      - web

  beat:
    image: *hubble-image
    container_name: hubble-beat
    environment:
      INTERNAL_IPS: ${INTERNAL_IPS}
    restart: always
    command:
      [
        "celery",
        "--app=hubble",
        "--loglevel=INFO",
        "--pidfile=/home/hubbleadm/tmp/beat.pid",
        "beat",
      ]
    depends_on:
      - broker
      - web

volumes:
  statics:
